/**
 * Contenido inicial de Café Travesía (carga inicial de la BD y MODO DEMO de la web/app).
 * Textos basados en el material de marca (Drive), cafetravesia.co y la propuesta.
 * Precios, stock, fichas sensoriales y contactos son EDITABLES desde el CMS: confírmalos con el cliente.
 */
const D = (s: string) => new Date(s);
/** ID determinista de 36 caracteres para hijos (variantes, módulos, lecciones, quizzes). */
export const childId = (parentId: string, kind: number, i: number, j = 0) =>
  `${parentId.slice(0, 24)}${kind.toString(16)}${i.toString(16).padStart(3, '0')}${j.toString(16).padStart(4, '0')}${parentId.slice(-4)}`;
const img = (n: string) => `/brand/fotos/${n}.webp`;

export const seedIds = {
  caicedo: '0f1a6b52-3c1d-4b8e-9a01-000000000001',
  cima: '0f1a6b52-3c1d-4b8e-9a01-000000000002',
  honey: '0f1a6b52-3c1d-4b8e-9a01-000000000003',
  casa: '0f1a6b52-3c1d-4b8e-9a01-000000000004',
  descafe: '0f1a6b52-3c1d-4b8e-9a01-000000000005',
  v60: '0f1a6b52-3c1d-4b8e-9a01-000000000006',
  prensa: '0f1a6b52-3c1d-4b8e-9a01-000000000007',
  mug: '0f1a6b52-3c1d-4b8e-9a01-000000000008',
  kit: '0f1a6b52-3c1d-4b8e-9a01-000000000009',
  cata: '0f1a6b52-3c1d-4b8e-9a01-000000000010',
  tour: '0f1a6b52-3c1d-4b8e-9a01-000000000011',
  gorra: '0f1a6b52-3c1d-4b8e-9a01-000000000012',
  cFund: '1c0e5a10-7d2b-4c11-8f00-000000000001',
  cEspresso: '1c0e5a10-7d2b-4c11-8f00-000000000002',
  cTueste: '1c0e5a10-7d2b-4c11-8f00-000000000003',
  cFiltrados: '1c0e5a10-7d2b-4c11-8f00-000000000004',
  pExplorador: '2a7d3e20-5b6c-4a22-9e00-000000000001',
  pMaestro: '2a7d3e20-5b6c-4a22-9e00-000000000002',
  pDuo: '2a7d3e20-5b6c-4a22-9e00-000000000003',
  pOficina: '2a7d3e20-5b6c-4a22-9e00-000000000004',
  pEquipo: '2a7d3e20-5b6c-4a22-9e00-000000000005',
} as const;

type V = { id: string; name: string; weightG?: number | null; grind?: string | null; priceCop: number; compareAtCop?: number | null; stock: number; sku: string; eventAt?: Date | null; sortOrder: number };
const variants = (pid: string, sku: string, rows: Omit<V, 'id' | 'sku' | 'sortOrder'>[]): (V & { productId: string })[] =>
  rows.map((r, i) => ({ ...r, id: childId(pid, 1, i), productId: pid, sku: `${sku}-${i + 1}`, sortOrder: i }));

const coffeeVariants = (pid: string, sku: string, p340: number, p500: number, stock = 60) =>
  variants(pid, sku, [
    { name: '340 g · En grano', weightG: 340, grind: 'grano', priceCop: p340, stock },
    { name: '340 g · Molido', weightG: 340, grind: 'media', priceCop: p340, stock },
    { name: '500 g · En grano', weightG: 500, grind: 'grano', priceCop: p500, stock: Math.round(stock / 2) },
    { name: '500 g · Molido', weightG: 500, grind: 'media', priceCop: p500, stock: Math.round(stock / 2) },
  ]);

export const seedProducts = [
  {
    id: seedIds.caicedo,
    slug: 'travesia-caicedo',
    name: 'Travesía Caicedo',
    subtitle: 'Nuestro origen · Caicedo, Antioquia',
    kind: 'coffee' as const,
    category: 'Origen único',
    description:
      'El café con el que empezó todo. Lotes de altura de familias caficultoras de **Caicedo, Antioquia**, tostado en pequeños lotes para resaltar su dulzura natural.\n\nUn perfil redondo y dulce, con notas de **chocolate y panela**, ideal para el día a día: va igual de bien en greca, prensa francesa o espresso.',
    story:
      'Caicedo es un pueblo de montaña al occidente de Antioquia, donde el café no solo se cultiva: se vive. Allá nació nuestra historia.\n\nSeleccionamos cereza por cereza con las familias de la vereda, secamos al sol y tostamos nosotros mismos. Cada bolsa lleva un pedazo de montaña y tradición.',
    originRegion: 'Caicedo, Antioquia',
    originFarm: 'Fincas familiares aliadas',
    producer: 'Familias caficultoras de Caicedo',
    altitudeM: 1900,
    variety: 'Castillo y Caturra',
    process: 'Lavado',
    roastLevel: 'Medio',
    profile: { tueste: 5, acidez: 5, cuerpo: 7, dulzor: 8, amargor: 3, complejidad: 6 },
    tastingNotes: ['Chocolate', 'Panela', 'Nuez'],
    brewMethods: ['Espresso', 'Prensa francesa', 'Greca', 'V60'],
    themeColor: '#111A31',
    accentColor: '#EB9A37',
    imageUrl: img('manos-cafe-caicedo'),
    gallery: [img('manos-cafe-caicedo'), img('latte-travesia')],
    badges: ['Más vendido'],
    isFeatured: true,
    isSeasonal: false,
    subscriptionEligible: true,
    ratingAvg: 4.9,
    ratingCount: 128,
    sortOrder: 1,
    seoTitle: 'Café de origen Caicedo, Antioquia | Café Travesía',
    seoDescription: 'Café especial de Caicedo con notas de chocolate y panela. Tostado en pequeños lotes y enviado recién empacado a toda Colombia.',
  },
  {
    id: seedIds.cima,
    slug: 'cima-del-viento',
    name: 'Cima del Viento',
    subtitle: 'Edición de temporada · Microlote',
    kind: 'coffee' as const,
    category: 'Edición limitada',
    description:
      'Un microlote de lo más alto de la cordillera, donde el viento enfría las noches y la cereza madura despacio.\n\nTaza **brillante y floral**, con acidez cítrica y final largo a caramelo. Para filtrados que se toman sin afán.',
    story: 'Cosechado en la parte alta de la vereda, a más de 2.000 metros. Solo unos cuantos sacos por cosecha: cuando se acaba, se acaba hasta el próximo año.',
    originRegion: 'Caicedo, Antioquia',
    originFarm: 'Finca La Cima',
    producer: 'Familia aliada de la vereda',
    altitudeM: 2050,
    variety: 'Caturra',
    process: 'Lavado de fermentación extendida',
    roastLevel: 'Claro',
    profile: { tueste: 3, acidez: 8, cuerpo: 5, dulzor: 7, amargor: 2, complejidad: 9 },
    tastingNotes: ['Jazmín', 'Mandarina', 'Caramelo'],
    brewMethods: ['V60', 'Chemex', 'AeroPress'],
    themeColor: '#4D6630',
    accentColor: '#F5C27A',
    imageUrl: img('taza-frase'),
    gallery: [img('taza-frase')],
    badges: ['Edición limitada', 'Altitud alta'],
    isFeatured: true,
    isSeasonal: true,
    subscriptionEligible: true,
    ratingAvg: 4.8,
    ratingCount: 42,
    sortOrder: 2,
    seoTitle: 'Cima del Viento, microlote de temporada | Café Travesía',
    seoDescription: 'Microlote floral y cítrico de más de 2.000 msnm. Edición limitada de temporada.',
  },
  {
    id: seedIds.honey,
    slug: 'honey-de-la-vereda',
    name: 'Honey de la Vereda',
    subtitle: 'Proceso honey · Dulce y frutal',
    kind: 'coffee' as const,
    category: 'Procesos especiales',
    description: 'Secado con parte del mucílago de la cereza para una taza **dulce, frutal y sedosa**: frutos rojos, miel y cacao.',
    story: 'Un experimento que salió tan bien que se quedó. El proceso honey requiere paciencia y mucho cuidado en el secado: lo hacemos en camas africanas, volteando el grano a mano.',
    originRegion: 'Caicedo, Antioquia',
    originFarm: 'Fincas aliadas',
    producer: 'Familias caficultoras de Caicedo',
    altitudeM: 1850,
    variety: 'Castillo',
    process: 'Honey',
    roastLevel: 'Medio claro',
    profile: { tueste: 4, acidez: 6, cuerpo: 6, dulzor: 9, amargor: 2, complejidad: 8 },
    tastingNotes: ['Frutos rojos', 'Miel', 'Cacao'],
    brewMethods: ['V60', 'Prensa francesa', 'Cold brew'],
    themeColor: '#B23A2E',
    accentColor: '#F5C27A',
    imageUrl: img('latte-travesia'),
    gallery: [img('latte-travesia')],
    badges: ['Nuevo'],
    isFeatured: true,
    isSeasonal: false,
    subscriptionEligible: true,
    ratingAvg: 4.9,
    ratingCount: 57,
    sortOrder: 3,
    seoTitle: 'Café proceso honey de Caicedo | Café Travesía',
    seoDescription: 'Café honey dulce y frutal: frutos rojos, miel y cacao. Tostado en Antioquia.',
  },
  {
    id: seedIds.casa,
    slug: 'blend-de-la-casa',
    name: 'Blend de la Casa',
    subtitle: 'El de la barra en Florida',
    kind: 'coffee' as const,
    category: 'Blend',
    description: 'El café que servimos en nuestra barra del **Parque Comercial Florida**. Cuerpo alto, dulce y con buen crema: perfecto para espresso y bebidas con leche.',
    story: 'Lo diseñamos con nuestros baristas para que un capuchino sepa a Travesía. Mezcla de lotes de Caicedo con tueste medio-oscuro.',
    originRegion: 'Antioquia',
    originFarm: 'Lotes seleccionados',
    producer: 'Café Travesía',
    altitudeM: 1800,
    variety: 'Castillo, Caturra y Colombia',
    process: 'Lavado',
    roastLevel: 'Medio oscuro',
    profile: { tueste: 7, acidez: 3, cuerpo: 8, dulzor: 7, amargor: 5, complejidad: 5 },
    tastingNotes: ['Cacao', 'Caramelo', 'Avellana'],
    brewMethods: ['Espresso', 'Moka', 'Greca'],
    themeColor: '#3A2418',
    accentColor: '#EB9A37',
    imageUrl: img('barra-travesia'),
    gallery: [img('barra-travesia'), img('frappe-caramelo')],
    badges: [],
    isFeatured: true,
    isSeasonal: false,
    subscriptionEligible: true,
    ratingAvg: 4.7,
    ratingCount: 91,
    sortOrder: 4,
    seoTitle: 'Blend de la casa para espresso | Café Travesía',
    seoDescription: 'El café de nuestra barra en Florida, Medellín: cuerpo alto con notas de cacao y caramelo.',
  },
  {
    id: seedIds.descafe,
    slug: 'descafeinado-natural',
    name: 'Descafeinado Natural',
    subtitle: 'Todo el sabor, sin desvelo',
    kind: 'coffee' as const,
    category: 'Descafeinado',
    description: 'Descafeinado con proceso de **caña de azúcar** (acetato de etilo natural). Dulce, suave y con notas de panela para la taza de la noche.',
    story: 'Para quienes aman el café pero no a las 10 de la noche.',
    originRegion: 'Antioquia',
    originFarm: 'Lotes seleccionados',
    producer: 'Café Travesía',
    altitudeM: 1750,
    variety: 'Castillo',
    process: 'Descafeinado EA (caña)',
    roastLevel: 'Medio',
    profile: { tueste: 5, acidez: 3, cuerpo: 6, dulzor: 7, amargor: 3, complejidad: 4 },
    tastingNotes: ['Panela', 'Galleta', 'Cacao suave'],
    brewMethods: ['Prensa francesa', 'Greca', 'Espresso'],
    themeColor: '#5B3A26',
    accentColor: '#FBE7C9',
    imageUrl: img('latte-travesia'),
    gallery: [],
    badges: [],
    isFeatured: false,
    isSeasonal: false,
    subscriptionEligible: true,
    ratingAvg: 4.6,
    ratingCount: 23,
    sortOrder: 5,
    seoTitle: null,
    seoDescription: null,
  },
  {
    id: seedIds.v60,
    slug: 'kit-v60-travesia',
    name: 'Kit V60 Travesía',
    subtitle: 'Gotero, filtros y guía de preparación',
    kind: 'accessory' as const,
    category: 'Barismo en casa',
    description: 'Todo para empezar con métodos de filtrado: gotero cerámico V60, 100 filtros y nuestra guía impresa con recetas para cada café.',
    story: null,
    originRegion: null, originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: ['V60'],
    themeColor: '#EFE6D6', accentColor: '#111A31',
    imageUrl: img('taza-frase'), gallery: [], badges: [],
    isFeatured: false, isSeasonal: false, subscriptionEligible: false, ratingAvg: 4.8, ratingCount: 19, sortOrder: 10, seoTitle: null, seoDescription: null,
  },
  {
    id: seedIds.prensa,
    slug: 'prensa-francesa',
    name: 'Prensa francesa 600 ml',
    subtitle: 'Vidrio de borosilicato y acero',
    kind: 'accessory' as const,
    category: 'Barismo en casa',
    description: 'El método más sencillo para una taza con cuerpo. Capacidad para 3-4 tazas.',
    story: null,
    originRegion: null, originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: ['Prensa francesa'],
    themeColor: '#EFE6D6', accentColor: '#111A31',
    imageUrl: img('barra-travesia'), gallery: [], badges: [],
    isFeatured: false, isSeasonal: false, subscriptionEligible: false, ratingAvg: 4.7, ratingCount: 12, sortOrder: 11, seoTitle: null, seoDescription: null,
  },
  {
    id: seedIds.mug,
    slug: 'mug-travesia',
    name: 'Mug Travesía',
    subtitle: 'Cerámica esmaltada · 350 ml',
    kind: 'merch' as const,
    category: 'Mugs y termos',
    description: 'Nuestro mug de cerámica con el logotipo en azul noche y el lema en ámbar.',
    story: null,
    originRegion: null, originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: [],
    themeColor: '#F8F3EA', accentColor: '#111A31',
    imageUrl: img('latte-travesia'), gallery: [], badges: [],
    isFeatured: false, isSeasonal: false, subscriptionEligible: false, ratingAvg: 4.9, ratingCount: 31, sortOrder: 20, seoTitle: null, seoDescription: null,
  },
  {
    id: seedIds.gorra,
    slug: 'gorra-travesia',
    name: 'Gorra Travesía',
    subtitle: 'Azul noche · bordado ámbar',
    kind: 'merch' as const,
    category: 'Ropa',
    description: 'La gorra de nuestro equipo de barra. Algodón, correa ajustable y logotipo bordado.',
    story: null,
    originRegion: null, originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: [],
    themeColor: '#111A31', accentColor: '#EB9A37',
    imageUrl: img('aromatica-frutos'), gallery: [], badges: [],
    isFeatured: false, isSeasonal: false, subscriptionEligible: false, ratingAvg: 4.8, ratingCount: 9, sortOrder: 21, seoTitle: null, seoDescription: null,
  },
  {
    id: seedIds.kit,
    slug: 'kit-regalo-travesia',
    name: 'Kit Regalo Travesía',
    subtitle: '2 cafés + mug + tarjeta',
    kind: 'kit' as const,
    category: 'Kits de regalo',
    description: 'Una caja para regalar origen: Travesía Caicedo y Honey de la Vereda (250 g c/u), mug Travesía y tarjeta con mensaje personalizado.',
    story: null,
    originRegion: null, originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: [],
    themeColor: '#EB9A37', accentColor: '#111A31',
    imageUrl: img('manos-cafe-caicedo'), gallery: [], badges: ['Ideal para regalar'],
    isFeatured: true, isSeasonal: false, subscriptionEligible: false, ratingAvg: 5, ratingCount: 14, sortOrder: 15, seoTitle: null, seoDescription: null,
  },
  {
    id: seedIds.cata,
    slug: 'cata-sensorial-medellin',
    name: 'Cata sensorial en Florida',
    subtitle: 'Experiencia · Medellín · 2 horas',
    kind: 'experience' as const,
    category: 'Catas y tours',
    description: 'Aprende a catar como los profesionales en nuestra barra del Parque Comercial Florida: rueda de sabores, 4 orígenes y métodos de preparación. Incluye bolsa de 250 g.',
    story: null,
    originRegion: 'Medellín', originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: [],
    themeColor: '#1E2A4A', accentColor: '#EB9A37',
    imageUrl: img('barra-travesia'), gallery: [], badges: ['Cupos limitados'],
    isFeatured: false, isSeasonal: false, subscriptionEligible: false, ratingAvg: 5, ratingCount: 26, sortOrder: 30, seoTitle: null, seoDescription: null,
  },
  {
    id: seedIds.tour,
    slug: 'travesia-cafetera-caicedo',
    name: 'Travesía cafetera en Caicedo',
    subtitle: 'Tour de un día a la finca',
    kind: 'experience' as const,
    category: 'Catas y tours',
    description: 'Vive el origen: visita fincas en Caicedo, recolecta, conoce el beneficio y tuesta tu propio lote con nuestro equipo. Incluye almuerzo campesino y transporte desde Medellín.',
    story: null,
    originRegion: 'Caicedo, Antioquia', originFarm: null, producer: null, altitudeM: null, variety: null, process: null, roastLevel: null, profile: null,
    tastingNotes: [], brewMethods: [],
    themeColor: '#4D6630', accentColor: '#F5C27A',
    imageUrl: img('manos-cafe-caicedo'), gallery: [], badges: ['Experiencia de origen'],
    isFeatured: false, isSeasonal: false, subscriptionEligible: false, ratingAvg: 5, ratingCount: 11, sortOrder: 31, seoTitle: null, seoDescription: null,
  },
];

export const seedVariants = [
  ...coffeeVariants(seedIds.caicedo, 'CT-CAI', 42900, 58900, 120),
  ...coffeeVariants(seedIds.cima, 'CT-CIM', 54900, 74900, 24),
  ...coffeeVariants(seedIds.honey, 'CT-HON', 49900, 67900, 40),
  ...coffeeVariants(seedIds.casa, 'CT-CAS', 39900, 54900, 90),
  ...coffeeVariants(seedIds.descafe, 'CT-DES', 44900, 61900, 30),
  ...variants(seedIds.v60, 'CT-V60', [{ name: 'Kit completo', priceCop: 129900, compareAtCop: 149900, stock: 15 }]),
  ...variants(seedIds.prensa, 'CT-PRE', [{ name: '600 ml', priceCop: 89900, stock: 12 }]),
  ...variants(seedIds.mug, 'CT-MUG', [{ name: '350 ml', priceCop: 39900, stock: 40 }]),
  ...variants(seedIds.gorra, 'CT-GOR', [{ name: 'Talla única', priceCop: 59900, stock: 25 }]),
  ...variants(seedIds.kit, 'CT-KIT', [{ name: 'Caja regalo', priceCop: 139900, compareAtCop: 159900, stock: 20 }]),
  ...variants(seedIds.cata, 'CT-CATA', [
    { name: 'Sábado 7 nov · 10:00 a. m.', priceCop: 95000, stock: 12, eventAt: D('2026-11-07T15:00:00Z') },
    { name: 'Sábado 21 nov · 10:00 a. m.', priceCop: 95000, stock: 12, eventAt: D('2026-11-21T15:00:00Z') },
  ]),
  ...variants(seedIds.tour, 'CT-TOUR', [
    { name: 'Domingo 15 nov', priceCop: 320000, stock: 10, eventAt: D('2026-11-15T11:00:00Z') },
    { name: 'Domingo 13 dic', priceCop: 320000, stock: 10, eventAt: D('2026-12-13T11:00:00Z') },
  ]),
].map((v) => ({ ...v, compareAtCop: v.compareAtCop ?? null, weightG: v.weightG ?? null, grind: v.grind ?? null, eventAt: v.eventAt ?? null, isActive: true }));

export const seedPlans = [
  { id: seedIds.pExplorador, slug: 'explorador', name: 'Explorador', tagline: 'Un origen distinto cada mes', description: 'Una bolsa de 340 g al mes, elegida por nuestros tostadores.', audience: 'personal' as const, frequencyWeeks: 4, bagsPerDelivery: 1, bagWeightG: 340, priceCop: 39900, compareAtCop: 46900, includesAcademy: false, benefits: ['1 bolsa de 340 g al mes', 'Envío gratis', '15 % menos que en tienda', 'Pausa o cancela cuando quieras'], imageUrl: '/brand/fotos/manos-cafe-caicedo.webp', isHighlighted: false, sortOrder: 1 },
  { id: seedIds.pMaestro, slug: 'maestro-premium', name: 'Maestro Premium', tagline: 'Café + Academia Travesía', description: 'Dos bolsas al mes y acceso completo a la Academia.', audience: 'personal' as const, frequencyWeeks: 4, bagsPerDelivery: 2, bagWeightG: 340, priceCop: 89900, compareAtCop: 119800, includesAcademy: true, benefits: ['2 bolsas de 340 g al mes', 'Todos los cursos de la Academia', 'Ediciones de temporada primero', 'Envío gratis'], imageUrl: '/brand/fotos/latte-travesia.webp', isHighlighted: true, sortOrder: 2 },
  { id: seedIds.pDuo, slug: 'duo-quincenal', name: 'Dúo Quincenal', tagline: 'Para casas cafeteras', description: 'Una bolsa cada dos semanas para no quedarte nunca sin café.', audience: 'personal' as const, frequencyWeeks: 2, bagsPerDelivery: 1, bagWeightG: 340, priceCop: 37900, compareAtCop: 42900, includesAcademy: false, benefits: ['1 bolsa cada 2 semanas', 'Envío gratis', 'Elige grano o molido'], imageUrl: '/brand/fotos/barra-travesia.webp', isHighlighted: false, sortOrder: 3 },
  { id: seedIds.pOficina, slug: 'oficina', name: 'Oficina', tagline: 'Café de especialidad para tu equipo', description: '2 kg al mes con factura electrónica.', audience: 'empresa' as const, frequencyWeeks: 4, bagsPerDelivery: 4, bagWeightG: 500, priceCop: 219000, compareAtCop: 259600, includesAcademy: false, benefits: ['4 bolsas de 500 g al mes', 'Factura electrónica', 'Capacitación de barismo para el equipo', 'Asesor dedicado'], imageUrl: '/brand/fotos/florida-lugar-diferente.webp', isHighlighted: true, sortOrder: 10 },
  { id: seedIds.pEquipo, slug: 'equipo-grande', name: 'Equipo grande', tagline: 'Para 30+ personas', description: '5 kg al mes, entregas quincenales.', audience: 'empresa' as const, frequencyWeeks: 2, bagsPerDelivery: 5, bagWeightG: 500, priceCop: 259000, compareAtCop: null, includesAcademy: true, benefits: ['5 bolsas de 500 g cada 2 semanas', 'Academia para todo el equipo', 'Factura electrónica', 'Préstamo de molino'], imageUrl: '/brand/fotos/florida-te-esperamos.webp', isHighlighted: false, sortOrder: 11 },
].map((p) => ({ ...p, isActive: true }));

type L = { title: string; summary: string; durationS: number; isPreview?: boolean; content?: string };
type M = { title: string; lessons: L[]; quiz?: { title: string; questions: { prompt: string; options: string[]; correctIndex: number; explanation: string }[] } };
const course = (id: string, base: Record<string, unknown>, modules: M[]) => ({ id, base, modules });

export const seedCourses = [
  course(
    seedIds.cFund,
    {
      slug: 'fundamentos-del-grano',
      title: 'Fundamentos del Grano',
      subtitle: 'Del cafeto a la taza: entiende qué hace especial a un café',
      description: '¿Sabías que no todos los cafés son especiales? En este curso gratuito recorremos el viaje del grano desde la finca en Caicedo hasta tu taza: variedades, procesos, puntaje SCA y cómo leer una etiqueta.',
      coverUrl: '/brand/fotos/manos-cafe-caicedo.webp',
      level: 'principiante',
      category: 'Origen',
      instructorName: 'Gabriel Travesía',
      instructorTitle: 'Fundador y caficultor',
      instructorBio: 'Creció entre cafetales en Caicedo, Antioquia. Hoy lidera el tueste y las alianzas con las familias de la vereda.',
      priceCop: 0,
      isFree: true,
      includedInSubscription: true,
      whatYouLearn: ['Qué es un café especial (más de 80 puntos SCA)', 'Variedades y procesos: lavado, honey y natural', 'Cómo leer la etiqueta de una bolsa', 'Por qué el origen lo cambia todo'],
      requirements: ['Ninguno: solo ganas de aprender'],
      durationMin: 45,
      ratingAvg: 4.9,
      ratingCount: 312,
      isPublished: true,
      isFeatured: true,
      sortOrder: 1,
    },
    [
      { title: 'El origen', lessons: [
        { title: 'Bienvenida a la travesía', summary: 'Quiénes somos y cómo aprovechar el curso.', durationS: 240, isPreview: true, content: 'Venimos desde **Caicedo, Antioquia**, donde el café no solo se cultiva, sino que se vive.\n\nEn este curso vas a entender por qué no todos los cafés son iguales.' },
        { title: 'Del cafeto a la cereza', summary: 'Ciclo del cultivo, sombra y altura.', durationS: 540 },
        { title: '¿Qué es un café especial?', summary: 'La escala SCA y los defectos.', durationS: 600, content: 'Un café especial es aquel que obtiene **más de 80 puntos** en la escala de la SCA. Eso significa:\n\n- Mejor aroma\n- Sabor más limpio\n- Cero defectos primarios' },
      ], quiz: { title: 'Evaluación: el origen', questions: [
        { prompt: '¿Desde qué puntaje SCA se considera especial un café?', options: ['70 puntos', '80 puntos', '90 puntos'], correctIndex: 1, explanation: 'La SCA considera especial un café desde 80 puntos.' },
        { prompt: '¿Qué aporta la altura al grano?', options: ['Maduración más lenta y mayor complejidad', 'Más cafeína', 'Granos más grandes siempre'], correctIndex: 0, explanation: 'El clima frío de altura hace que la cereza madure despacio y concentre azúcares.' },
      ] } },
      { title: 'Procesos y etiqueta', lessons: [
        { title: 'Lavado, honey y natural', summary: 'Cómo el beneficio cambia la taza.', durationS: 660 },
        { title: 'Cómo leer una etiqueta', summary: 'Variedad, proceso, altura, fecha de tueste.', durationS: 420 },
      ] },
    ],
  ),
  course(
    seedIds.cEspresso,
    {
      slug: 'maestria-en-extraccion-espresso',
      title: 'Maestría en Extracción: Espresso',
      subtitle: 'Domina molienda, dosis, tiempo y textura de leche',
      description: 'El curso insignia de nuestra barra en Florida. Aprende a calibrar un espresso, diagnosticar sub y sobre extracción y texturizar leche para latte art.',
      coverUrl: '/brand/fotos/latte-travesia.webp',
      level: 'intermedio',
      category: 'Barismo',
      instructorName: 'Alex Travesía',
      instructorTitle: 'Barista líder · Florida',
      instructorBio: 'Barista campeón regional y formador del equipo de barra de Café Travesía en Medellín.',
      priceCop: 149000,
      compareAtCop: 189000,
      isFree: false,
      includedInSubscription: true,
      whatYouLearn: ['Calibrar receta: dosis, rendimiento y tiempo', 'Diagnosticar extracción por sabor', 'Texturizar leche y latte art básico', 'Mantenimiento de máquina y molino'],
      requirements: ['Acceso a una máquina de espresso (casera o profesional)'],
      durationMin: 165,
      ratingAvg: 4.9,
      ratingCount: 184,
      isPublished: true,
      isFeatured: true,
      sortOrder: 2,
    },
    [
      { title: 'Calibración', lessons: [
        { title: 'Anatomía del espresso', summary: 'Crema, cuerpo y corazón.', durationS: 480, isPreview: true },
        { title: 'Calibración de molienda fina', summary: 'El ajuste que lo cambia todo.', durationS: 720 },
        { title: 'Receta: dosis, rendimiento y tiempo', summary: 'Ratio 1:2 y cómo moverlo.', durationS: 840 },
      ] },
      { title: 'Leche y latte art', lessons: [
        { title: 'Texturizar leche', summary: 'Aire, rotación y temperatura.', durationS: 780 },
        { title: 'Corazón y tulipán', summary: 'Tus primeros diseños.', durationS: 900 },
      ], quiz: { title: 'Evaluación final', questions: [
        { prompt: 'Un espresso ácido y aguado en 18 s indica…', options: ['Sobreextracción', 'Subextracción', 'Extracción ideal'], correctIndex: 1, explanation: 'Poco tiempo y sabor ácido = subextracción: muele más fino.' },
        { prompt: 'Ratio clásico de un espresso', options: ['1:1', '1:2', '1:5'], correctIndex: 1, explanation: '1:2 (p. ej. 18 g de café → 36 g de bebida) es el punto de partida clásico.' },
      ] } },
    ],
  ),
  course(
    seedIds.cTueste,
    {
      slug: 'la-ciencia-del-tueste',
      title: 'La Ciencia detrás del Tueste Perfecto',
      subtitle: 'Reacciones de Maillard, curvas y perfiles',
      description: 'Descubre la química detrás del aroma y el sabor: cómo el calor transforma azúcares y aminoácidos y cómo diseñar perfiles de tueste.',
      coverUrl: '/brand/fotos/barra-travesia.webp',
      level: 'avanzado',
      category: 'Tueste',
      instructorName: 'Gabriel Travesía',
      instructorTitle: 'Maestro tostador',
      instructorBio: 'Responsable del tueste de todos los lotes de Café Travesía.',
      priceCop: 189000,
      isFree: false,
      includedInSubscription: true,
      whatYouLearn: ['Fases del tueste', 'Reacciones de Maillard y caramelización', 'Leer una curva de tueste', 'Diseñar un perfil para filtrado y otro para espresso'],
      requirements: ['Haber tomado Fundamentos del Grano (recomendado)'],
      durationMin: 210,
      ratingAvg: 4.8,
      ratingCount: 67,
      isPublished: true,
      isFeatured: false,
      sortOrder: 3,
    },
    [
      { title: 'Química del tueste', lessons: [
        { title: 'Introducción al tostado', summary: 'Secado, Maillard y desarrollo.', durationS: 520, isPreview: true },
        { title: 'Las reacciones de Maillard', summary: 'El alma del aroma.', durationS: 1440 },
      ] },
      { title: 'Perfiles', lessons: [
        { title: 'Curvas de tueste', summary: 'RoR, primer crack y desarrollo.', durationS: 960 },
        { title: 'Perfil para espresso vs. filtrado', summary: 'Mismo grano, dos destinos.', durationS: 1080 },
      ] },
    ],
  ),
  course(
    seedIds.cFiltrados,
    {
      slug: 'metodos-de-filtrado',
      title: 'Métodos de Filtrado en Casa',
      subtitle: 'V60, Chemex, prensa francesa y AeroPress',
      description: 'Recetas probadas para preparar en casa un café como el de la barra. Molienda, temperatura y vertido para cada método.',
      coverUrl: '/brand/fotos/taza-frase.webp',
      level: 'principiante',
      category: 'Preparación',
      instructorName: 'Alex Travesía',
      instructorTitle: 'Barista líder · Florida',
      priceCop: 89000,
      isFree: false,
      includedInSubscription: true,
      whatYouLearn: ['Receta base para V60 y Chemex', 'Prensa francesa sin sedimento', 'AeroPress invertida', 'Ajustar una receta según el sabor'],
      requirements: ['Un método de filtrado y una balanza (ideal)'],
      durationMin: 95,
      ratingAvg: 4.8,
      ratingCount: 143,
      isPublished: true,
      isFeatured: true,
      sortOrder: 4,
    },
    [
      { title: 'Métodos', lessons: [
        { title: 'Agua, molienda y temperatura', summary: 'Las tres variables.', durationS: 420, isPreview: true },
        { title: 'V60 paso a paso', summary: 'Bloom y vertidos.', durationS: 720 },
        { title: 'Chemex: receta paso a paso', summary: 'Taza limpia y brillante.', durationS: 660 },
        { title: 'Prensa francesa y AeroPress', summary: 'Inmersión.', durationS: 780 },
      ] },
    ],
  ),
];

export const seedPosts = [
  {
    slug: 'no-todos-los-cafes-son-especiales',
    title: '¿Sabías que no todos los cafés son especiales?',
    excerpt: 'Un café especial obtiene más de 80 puntos en la escala SCA. Te contamos qué significa y por qué se nota en la taza.',
    category: 'Cultura cafetera',
    tags: ['café especial', 'SCA', 'calidad'],
    coverUrl: '/brand/fotos/manos-cafe-caicedo.webp',
    authorName: 'Equipo Travesía',
    readingMin: 4,
    isFeatured: true,
    publishedAt: D('2026-09-02T14:00:00Z'),
    content:
      '## Más de 80 puntos\n\nUn café especial es aquel que obtiene **más de 80 puntos** en una escala de calidad internacional (SCA). Eso significa:\n\n- ✔ Mejor aroma\n- ✔ Sabor más limpio\n- ✔ Cero defectos\n\n## ¿Quién lo califica?\n\nCatadores certificados evalúan fragancia, sabor, acidez, cuerpo, balance y dulzor.\n\n## En Café Travesía\n\nCultivamos, tostamos y servimos café especial. Porque si vas a tomar café… **que sea de verdad**.',
  },
  {
    slug: 'de-donde-viene-tu-cafe',
    title: '¿Y vos sabés de dónde viene tu café?',
    excerpt: 'Un café de origen viene de una sola región, finca o comunidad. Así se preserva su identidad, su sabor y su historia.',
    category: 'Origen',
    tags: ['origen', 'Caicedo', 'Antioquia'],
    coverUrl: '/brand/fotos/taza-frase.webp',
    authorName: 'Equipo Travesía',
    readingMin: 5,
    isFeatured: false,
    publishedAt: D('2026-09-16T14:00:00Z'),
    content:
      'Eso lo cambia todo.\n\n## Café de origen\n\nUn café de origen viene de una sola región, finca o comunidad. Así se preserva su identidad, su sabor y su historia.\n\n## El nuestro\n\nEl nuestro viene de **Caicedo, Antioquia**. Y en cada taza, llevás un pedazo de montaña y tradición.',
  },
  {
    slug: 'como-preparar-chemex',
    title: 'Cómo preparar café en Chemex: receta paso a paso',
    excerpt: 'La receta de nuestra barra para una taza limpia, brillante y dulce en casa.',
    category: 'Preparación',
    tags: ['Chemex', 'recetas', 'filtrados'],
    coverUrl: '/brand/fotos/latte-travesia.webp',
    authorName: 'Alex Travesía',
    readingMin: 6,
    isFeatured: false,
    publishedAt: D('2026-09-30T14:00:00Z'),
    content:
      '## Lo que necesitas\n\n- 30 g de café molienda media-gruesa\n- 500 g de agua a 93 °C\n- Filtro Chemex enjuagado\n\n## Paso a paso\n\n1. **Bloom:** vierte 60 g de agua y espera 40 s.\n2. Vierte en espiral hasta 300 g.\n3. Completa 500 g y deja drenar (4:00 total).\n\n> Si sabe ácido, muele más fino. Si sabe amargo, más grueso.',
  },
  {
    slug: 'florida-nueva-parada',
    title: 'Florida: tu nueva parada cafetera en Medellín',
    excerpt: 'Llegamos al Parque Comercial Florida con lo mejor de nuestro café caicedeño. Un espacio pa’ trabajar, conversar o hacerle una pausa al caos.',
    category: 'Noticias',
    tags: ['Medellín', 'Florida', 'tienda'],
    coverUrl: '/brand/fotos/florida-te-esperamos.webp',
    authorName: 'Equipo Travesía',
    readingMin: 3,
    isFeatured: false,
    publishedAt: D('2026-08-20T14:00:00Z'),
    content:
      'Venimos desde Caicedo, Antioquia, donde el café no solo se cultiva, sino que se vive.\n\nY hoy… estamos en Medellín. Llegamos al **Parque Comercial Florida** con lo mejor de nuestro café caicedeño: un espacio pa’ vos, pa’ trabajar, pa’ conversar, pa’ hacerle una pausa al caos, o pa’ simplemente tomarte un buen café, como te gusta.\n\n¡Te estamos esperando!',
  },
];

export const seedStores = [
  {
    slug: 'florida',
    name: 'Café Travesía · Florida',
    kind: 'cafe' as const,
    address: 'Parque Comercial Florida, Medellín',
    city: 'Medellín',
    hours: ['Lunes a sábado · 9:00 a. m. – 8:00 p. m.', 'Domingos y festivos · 10:00 a. m. – 7:00 p. m.'],
    phone: null,
    mapUrl: 'https://maps.google.com/?q=Parque+Comercial+Florida+Medellin',
    menuUrl: null,
    imageUrl: '/brand/fotos/florida-lugar-diferente.webp',
    description: 'Un lugar diferente, el mismo sabor. Parqueadero gratis y a pasos del coworking.',
    lat: 6.2697,
    lng: -75.5786,
    sortOrder: 1,
  },
  {
    slug: 'caicedo',
    name: 'Nuestro origen · Caicedo',
    kind: 'finca' as const,
    address: 'Caicedo, Antioquia',
    city: 'Caicedo',
    hours: ['Visitas con reserva (Travesía cafetera)'],
    phone: null,
    mapUrl: 'https://maps.google.com/?q=Caicedo+Antioquia',
    menuUrl: null,
    imageUrl: '/brand/fotos/manos-cafe-caicedo.webp',
    description: 'Donde el café no solo se cultiva, sino que se vive. Tours de origen con reserva.',
    lat: 6.4053,
    lng: -75.9825,
    sortOrder: 2,
  },
].map((s) => ({ ...s, isActive: true }));

export const seedShippingZones = [
  { name: 'Valle de Aburrá', regions: [], cities: ['Medellín', 'Envigado', 'Itagüí', 'Sabaneta', 'Bello', 'La Estrella', 'Caldas', 'Copacabana', 'Girardota', 'Barbosa'], rateCop: 7000, freeFromCop: 99000, etaDays: '1-2 días hábiles', isDefault: false, sortOrder: 1 },
  { name: 'Resto de Antioquia', regions: ['Antioquia'], cities: [], rateCop: 11000, freeFromCop: 140000, etaDays: '2-3 días hábiles', isDefault: false, sortOrder: 2 },
  { name: 'Ciudades principales', regions: ['Bogotá D.C.', 'Valle del Cauca', 'Atlántico', 'Santander', 'Risaralda', 'Caldas', 'Quindío'], cities: [], rateCop: 13000, freeFromCop: 160000, etaDays: '2-4 días hábiles', isDefault: false, sortOrder: 3 },
  { name: 'Nacional', regions: [], cities: [], rateCop: 16000, freeFromCop: 180000, etaDays: '3-6 días hábiles', isDefault: true, sortOrder: 9 },
];

export const seedCoupons = [
  { code: 'BIENVENIDA10', description: '10 % en tu primera compra', kind: 'percent' as const, value: 10, scope: 'all' as const, minSubtotalCop: 0, maxUses: null, maxUsesPerUser: 1, isActive: true },
  { code: 'ENVIOGRATIS', description: 'Envío gratis desde $80.000', kind: 'free_shipping' as const, value: 0, scope: 'products' as const, minSubtotalCop: 80000, maxUses: 500, maxUsesPerUser: 2, isActive: true },
  { code: 'ACADEMIA20', description: '20 % en cursos', kind: 'percent' as const, value: 20, scope: 'courses' as const, minSubtotalCop: 0, maxUses: 200, maxUsesPerUser: 1, isActive: true },
];

/** Contenido editable del sitio (CMS: /admin/contenido). */
export const SITE_DEFAULTS = {
  'home.hero': {
    eyebrow: 'Café 100 % colombiano · Caicedo, Antioquia',
    title: 'Embárcate en una travesía de sabor',
    subtitle: 'Producido, tostado y preparado en Caicedo. Cada sorbo es un viaje al corazón de nuestra tierra.',
    primaryCta: { label: 'Descubrir mi café', href: '/tienda' },
    secondaryCta: { label: 'Ver suscripciones', href: '/suscripciones' },
    videoUrl: '/brand/video/caicedo-origen.mp4',
    posterUrl: '/brand/video/caicedo-jeep.webp',
    imageUrl: '/brand/fotos/manos-cafe-caicedo.webp',
  },
  'home.seasonal': {
    enabled: true,
    eyebrow: 'Edición temporada',
    title: 'Cima del Viento',
    subtitle: 'Microlote de más de 2.000 msnm · Jazmín, mandarina y caramelo',
    productSlug: 'cima-del-viento',
    color: '#4D6630',
  },
  'home.banner': { enabled: true, text: 'Envío gratis en el Valle de Aburrá desde $99.000 · Usa BIENVENIDA10 en tu primera compra', href: '/tienda' },
  'home.story': {
    title: 'Del grano a tu taza, sin escalas',
    body: 'Seleccionamos los mejores lotes de altura, los tostamos artesanalmente y los enviamos recién empacados para que disfrutes un perfil dulce con notas de chocolate y panela.',
    pillars: [
      { icon: 'finca', title: 'Selección de origen', text: 'Trabajamos con caficultores familiares que cuidan cada cereza.' },
      { icon: 'granos', title: 'Tueste fresco', text: 'Pequeños lotes para resaltar la dulzura natural.' },
      { icon: 'tienda-online', title: 'Entrega express', text: 'Empacado con válvula y envío en menos de 48 h.' },
    ],
  },
  about: {
    title: 'La esencia de lo que somos',
    intro: 'Venimos desde Caicedo, Antioquia, donde el café no solo se cultiva, sino que se vive. Allá nació nuestra historia, y hoy la servimos en Medellín.',
    body: 'Creemos en un modelo justo y sostenible: pagamos precios por encima del mercado, invertimos en procesos ecológicos y formamos a la nueva generación cafetera.',
    imageUrl: '/brand/fotos/manos-cafe-caicedo.webp',
  },
  impact: {
    title: 'El alma en cada grano, el respeto por la tierra',
    intro: 'Cada compra impulsa proyectos de reforestación y bienestar para las familias caficultoras de Caicedo.',
    stats: [
      { value: '+30 %', label: 'sobre el precio de mercado pagado al productor' },
      { value: '24', label: 'familias caficultoras aliadas' },
      { value: '3.200', label: 'árboles nativos sembrados' },
      { value: '100 %', label: 'trazabilidad del lote a la taza' },
    ],
    pillars: [
      { title: 'Comercio justo', text: 'Precio por encima del mercado y pago oportuno a cada familia.' },
      { title: 'Sostenibilidad', text: 'Cultivo bajo sombra, manejo de aguas mieles y empaques reciclables.' },
      { title: 'Nueva generación', text: 'Formación para jóvenes caficultores y baristas de la región.' },
    ],
  },
  faq: {
    items: [
      { q: '¿Cuándo se tuesta mi café?', a: 'Tostamos cada semana en pequeños lotes y despachamos en máximo 48 horas después del tueste.' },
      { q: '¿Hacen envíos a toda Colombia?', a: 'Sí. En el Valle de Aburrá entregamos en 1-2 días hábiles; al resto del país en 2-6 días hábiles.' },
      { q: '¿Puedo pausar o cancelar mi suscripción?', a: 'Cuando quieras, desde tu cuenta o la app: pausa, salta un envío, cambia de café o cancela sin penalidad.' },
      { q: '¿Qué medios de pago aceptan?', a: 'Tarjetas de crédito y débito, PSE, Nequi, Bancolombia y Daviplata a través de Wompi, la pasarela de Bancolombia.' },
      { q: '¿Los cursos dan certificado?', a: 'Sí. Al completar todas las lecciones y aprobar las evaluaciones recibes un certificado verificable en PDF.' },
      { q: '¿Venden al por mayor?', a: 'Sí, tenemos precios especiales para oficinas, restaurantes y distribuidores. Escríbenos desde la página de empresas.' },
    ],
  },
  contact: {
    email: 'info@cafetravesia.co',
    phone: '',
    whatsapp: '573147482358',
    address: 'Parque Comercial Florida, Medellín · Caicedo, Antioquia',
    hours: 'Lunes a sábado 9:00 a. m. – 8:00 p. m.',
    instagram: 'https://instagram.com/cafetravesia',
    facebook: 'https://facebook.com/cafetravesia',
    tiktok: 'https://tiktok.com/@cafetravesia',
  },
  app_links: { ios: '', android: '' },
  seo: {
    title: 'Café Travesía · Café especial de Caicedo, Antioquia',
    description: 'Cultivamos, tostamos y servimos café especial. Tienda en línea, suscripciones, academia de barismo y nuestra barra en el Parque Comercial Florida, Medellín.',
    ogImage: '/brand/fotos/manos-cafe-caicedo.webp',
  },
} as const;

export type SiteContentKey = keyof typeof SITE_DEFAULTS;
